### ISSUE TITLE
Make it possible again to parse PDB files with missing element columns (77-78)

### ISSUE THREAD

**Issue by daurer** [FXIhub/spsim#8]
There should be a way that allows for parsing PDB files with and without having the element columns (77-78), some kind of hybrid between the code before and after commit fc920d802799376a47bfd4849a006b2698aa4d48

**Comment by mhantke** [comment]
I think this is dangerous because the atom name does not necessarily have to be the element name. I would prefer to be strict with only accepting files that follow the PDB format as described here:

http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

I fixed DNA.pdb to follow the PDB format with 93b8fb2351e4345820732c234944f00a4bea9f1c

**Comment by mhantke** [comment]
Suggest to close this issue.

**Comment by daurer** [comment]
Sounds good to me. Thanks for fixing!

**Comment by mhantke** [comment]
Actually it's stated explicitly:
"The element symbol is always present on each ATOM record"
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM
